builders:
  node_builder:
    import: "package:trinity_generator/trinity_generator.dart"
    builder_factories: ["nodeBuilder"]
    build_extensions: {".dart": [".readable.dart"]}
    auto_apply: dependents
    build_to: source