builders:
  node_readable:
    import: "package:trinity_generator/generator/builder.dart"
    builder_factories: ["nodeBuilder"]
    build_extensions: {".dart": [".g.dart"]}
    auto_apply: dependents
    build_to: source